[package]
name = "bouncerbot"
version = "0.1.0"
authors = ["Cauê Baasch de Souza <cauebs@pm.me>"]
edition = "2018"
license = "GPL-2+"

[dependencies]
tgbot = "0.11.0"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "sync", "time"] }
